---
###############################################################################
# Automatically reboot system after period of time.
###############################################################################
# Reference:
# * https://gist.github.com/hkoba/e05c91ebdd4e2ffd1d79e78e76cf1ff5
# * https://opensource.com/article/20/7/systemd-timers

- name: '{{
      "Auto reboot | filesystem | set " ~ os___app._systemd_dir ~ "/reboot.*"
    }}'
  when: os_cfg_reboot | length > 0
  notify:
    - 'Handlers | systemd reboot.timer'
  ansible.builtin.template:
    src: '{{ "systemd/" ~ item ~ ".j2" }}'
    dest: '{{ os___app._systemd_dir ~ "/" ~ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'reboot.timer'
    - 'reboot.service'

- name: '{{
      "Auto reboot | filesystem | remove " ~
      os___app._systemd_dir ~ "/reboot.*"
    }}'
  when: os_cfg_reboot | length == 0
  notify: 'Handlers | systemd'
  ansible.builtin.file:
    path: '{{ os___app._systemd_dir ~ "/" ~ item }}'
    state: absent
  loop:
    - 'reboot.timer'
    - 'reboot.service'
