---
# yamllint disable rule:line-length
###############################################################################
# Ensure locales are created.
###############################################################################
# Reference:
# * https://en.wikipedia.org/wiki/Locale_(computer_software)
# * https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue
# * https://serverfault.com/questions/959026/how-do-i-generate-and-set-the-locale-using-ansible
# yamllint enable rule:line-length

- name: 'Locales | install locales'
  community.general.locale_gen:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ os_locales }}'

- name: 'Locales | set system default locale'
  ansible.builtin.template:
    src: 'locale.j2'
    dest: '/etc/default/locale'
    owner: 'root'
    group: 'root'
    mode: '0644'
