---
- name: 'Install | packages'
  when: os___packages | length > 0
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages: '{{ os___packages }}'
    apt_srv_package_update_cache: true

- name: 'Locales'
  ansible.builtin.import_tasks: 'locales.yml'
- name: 'Timezone'
  ansible.builtin.import_tasks: 'timezone.yml'
- name: 'MOTD'
  ansible.builtin.import_tasks: 'motd.yml'

- name: 'Inotify limit'
  when: os_cfg_inotify_limit >= 0
  ansible.builtin.import_tasks: 'inotify_limit.yml'

- name: 'Skeleton files'
  when: os_cfg_skeleton_files | length > 0
  ansible.builtin.import_tasks: 'skeleton_files.yml'

- name: 'Auto reboot'
  ansible.builtin.import_tasks: 'auto_reboot.yml'

- name: 'Lockdown home'
  when: os_cfg_lockdown_home
  ansible.builtin.import_tasks: 'lockdown_home.yml'

- name: '/tmp'
  when: os_cfg_tmp_ram | length > 0
  ansible.builtin.import_tasks: 'tmp.yml'

- name: 'Flush handlers'
  ansible.builtin.meta: 'flush_handlers'  # Force cron restart.
