---
###############################################################################
# Add skeleton files.
###############################################################################

- name: 'Skeleton files | copy files'
  ansible.posix.synchronize:
    src: '{{ os_skeleton_files }}'
    dest: '/etc/skel'
    delete: true
    recursive: true
    archive: false
    checksum: true
  register: _os_skel

# Set immediately for new users to pull skeleton files correctly.
- name: 'Skeleton files | set file permissions'  # noqa: no-handler
  when: _os_skel.changed
  ansible.builtin.shell: >
    chown -R root:root /etc/skel &&
    find /etc/skel -type d -exec chmod 0755 {} \; &&
    find /etc/skel -type f -exec chmod 0644 {} \;
  changed_when: false
