---
###############################################################################
# Add skeleton files.
###############################################################################

- name: 'Skeleton files | filesystem | set /etc/skel'
  ansible.posix.synchronize:
    src: '{{ os_cfg_skeleton_files }}'
    dest: '/etc/skel'
    delete: true
    recursive: true
    archive: false
    checksum: true
  register: os__skel

# Set immediately for new users to pull skeleton files correctly.
- name: 'Skeleton files | cmd | set file permissions'
  when: os__skel.changed  # noqa: no-handler immediate.
  ansible.builtin.shell: >-
    chown -R root:root /etc/skel &&
    find /etc/skel -type d -exec chmod 0755 {} \; &&
    find /etc/skel -type f -exec chmod 0644 {} \;
  changed_when: false
