---
# yamllint disable rule:line-length
###############################################################################
# Set Timezone.
###############################################################################
# Use fully defined timezones from 'timedatectl list-timezones'. The following
# error may occur in virtual environments due to the fallback code current in
# ansible if using aliases (UTC vs. Etc/UTC):
#
# Force restart cron to ensure cron jobs do not mis-fire based on changes.
#
# Reference:
# * https://github.com/ansible-collections/community.general/issues/7498
# * https://docs.ansible.com/ansible/latest/collections/community/general/timezone_module.html
# * https://linuxize.com/post/how-to-set-or-change-timezone-on-debian-10/
# yamllint enable rule:line-length

- name: 'Timezone | set'
  notify: 'Handlers | restart cron'
  community.general.timezone:
    name: '{{ os_timezone }}'
