---
###############################################################################
# Use RAM for /tmp via tmpfs.
###############################################################################
# Debian mounts /tmp as tmpfs by default; just manage the mount options.
#
- name: '/tmp | create in-memory {{ os_tmp_ram }}'
  ansible.posix.mount:
    path: '{{ os_role_tmpfs }}'
    src: 'tmpfs'
    fstype: 'tmpfs'
    opts: 'mode=1777,nosuid,nodev,size={{ os_tmp_ram }}'
    state: 'mounted'
