---
- name: 'GPU passthrough | NOOP'
  ansible.builtin.debug:
    msg: 'GPU passthrough currently disabled until migrated'

# TODO(role): migrate original passthrough and re-enable.
# - name: 'GPU passthrough | nvidia guest'
#   when: >
#     os_gpu_brand | lower == 'nvidia' and
#     os_gpu_passthrough_mode | lower == 'guest'
#   ansible.builtin.include_tasks: 'nvidia_guest.yml'
#
# - name: 'GPU passthrough | nvidia host'
#   when: >
#     os_gpu_brand | lower == 'nvidia' and
#     os_gpu_passthrough_mode | lower == 'host'
#   ansible.builtin.include_tasks: 'nvidia_host.yml'
#
# - name: 'GPU passthrough | amd guest'
#   when: >
#     os_gpu_brand | lower == 'amd' and
#     os_gpu_passthrough_mode | lower == 'guest'
#   ansible.builtin.include_tasks: 'amd_guest.yml'
#
# - name: 'GPU passthrough | amd host'
#   when: >
#     os_gpu_brand | lower == 'amd' and
#     os_gpu_passthrough_mode | lower == 'host'
#   ansible.builtin.include_tasks: 'amd_host.yml'
